# Generated by Django 6.0 on 2025-12-14 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        editable=False,
                        max_length=6,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("reference_id", models.UUIDField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="ledger_tran_wallet__97b5a3_idx",
                    ),
                    models.Index(
                        fields=["reference_id"], name="ledger_tran_referen_cfd32f_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="transaction_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("type__in", ["debit", "credit"])),
                        name="transaction_type_valid",
                    ),
                ],
            },
        ),
    ]
