# Generated by Django 6.0 on 2025-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="transaction_type_valid",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="direction",
        ),
        migrations.AddField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("fee", "Fee"),
                    ("refund", "Refund"),
                ],
                default="transfer",
                editable=False,
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction__in", ["debit", "credit"])),
                name="transaction_direction_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["transfer", "fee", "refund"])),
                name="transaction_kind_valid",
            ),
        ),
    ]
